-- Multi-tenancy baseline.
--
-- The previous schema was generated by Hibernate ddl-auto=update and carried no tenant
-- column. It held no production data, so this migration recreates it from scratch rather
-- than adding a nullable column and backfilling. From here the schema belongs to Flyway.

DROP TABLE IF EXISTS affected_items CASCADE;
DROP TABLE IF EXISTS ticket_branch_links CASCADE;
DROP TABLE IF EXISTS contradictions CASCADE;
DROP TABLE IF EXISTS "constraints" CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS sources CASCADE;
DROP TABLE IF EXISTS initiatives CASCADE;

-- ---------------------------------------------------------------------------
-- Tenancy and identity.
--
-- tenants and users are deliberately NOT tenant-filtered: a login has to find the
-- user before any tenant is known, so filtering them would deadlock authentication.
-- ---------------------------------------------------------------------------

CREATE TABLE tenants (
    id         varchar(255) PRIMARY KEY,
    name       varchar(255) NOT NULL,
    -- Supplied at login alongside the email, since emails are only unique per tenant.
    -- Treated as immutable once issued: it ends up in login forms and bookmarks.
    slug       varchar(255) NOT NULL UNIQUE,
    created_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE users (
    id            varchar(255) PRIMARY KEY,
    tenant_id     varchar(255) NOT NULL REFERENCES tenants (id),
    email         varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    -- Every user is equal for now. The column exists so that introducing roles later
    -- is a behaviour change, not a migration of live data.
    role          varchar(255) NOT NULL,
    active        boolean      NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_users_tenant_email UNIQUE (tenant_id, email)
);

-- Only a hash is stored: a database leak must not yield usable refresh tokens.
CREATE TABLE refresh_tokens (
    id         varchar(255) PRIMARY KEY,
    tenant_id  varchar(255) NOT NULL REFERENCES tenants (id),
    user_id    varchar(255) NOT NULL REFERENCES users (id),
    token_hash varchar(255) NOT NULL UNIQUE,
    expires_at timestamp(6) with time zone NOT NULL,
    revoked_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL
);
CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);

-- ---------------------------------------------------------------------------
-- Integration connections.
--
-- A tenant owns any number of Jira sites and GitHub repos. These are shared service
-- accounts in the SMTP sense: account_id is a credential component belonging to the
-- tenant, never a link to a row in users.
-- ---------------------------------------------------------------------------

CREATE TABLE integration_connections (
    id                varchar(255) PRIMARY KEY,
    tenant_id         varchar(255) NOT NULL REFERENCES tenants (id),
    provider          varchar(255) NOT NULL,             -- JIRA | GITHUB
    label             varchar(255) NOT NULL,             -- "Prod Jira", "Team B GitHub"
    base_url          varchar(255) NOT NULL,
    account_id        varchar(255) NOT NULL,             -- Jira login email / GitHub owner
    repo              varchar(255) NOT NULL,             -- GitHub only; empty string for Jira
    -- Write-only. Encrypted with AES-GCM; never returned by any endpoint.
    secret_ciphertext text         NOT NULL,
    key_version       integer      NOT NULL,
    status            varchar(255) NOT NULL,             -- UNVERIFIED | OK | UNAUTHORIZED | ERROR
    last_error        text,
    created_at        timestamp(6) with time zone NOT NULL,
    -- Empty strings rather than NULLs above, so this constraint actually bites:
    -- in Postgres NULLs never conflict with each other.
    CONSTRAINT uk_connection_identity UNIQUE (tenant_id, provider, base_url, account_id, repo)
);
CREATE INDEX idx_connections_tenant_provider ON integration_connections (tenant_id, provider);

-- ---------------------------------------------------------------------------
-- Decision model. Every table below carries tenant_id and is filtered by Hibernate's
-- @TenantId on every read and stamped on every write.
-- ---------------------------------------------------------------------------

CREATE TABLE initiatives (
    id         varchar(255) PRIMARY KEY,
    tenant_id  varchar(255) NOT NULL REFERENCES tenants (id),
    name       varchar(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);
CREATE INDEX idx_initiatives_tenant_created ON initiatives (tenant_id, created_at DESC);

-- Replaces Initiative.jiraKey / Initiative.repo, which could each hold only one value.
CREATE TABLE initiative_connections (
    id            varchar(255) PRIMARY KEY,
    tenant_id     varchar(255) NOT NULL REFERENCES tenants (id),
    initiative_id varchar(255) NOT NULL REFERENCES initiatives (id) ON DELETE CASCADE,
    connection_id varchar(255) NOT NULL REFERENCES integration_connections (id) ON DELETE CASCADE,
    -- Jira project key or GitHub branch prefix scoping this initiative within the connection.
    scope_key     varchar(255) NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_initiative_connection UNIQUE (initiative_id, connection_id, scope_key)
);
CREATE INDEX idx_initiative_connections_tenant ON initiative_connections (tenant_id, initiative_id);

CREATE TABLE sources (
    id            varchar(255) PRIMARY KEY,
    tenant_id     varchar(255) NOT NULL REFERENCES tenants (id),
    initiative_id varchar(255) NOT NULL,
    type          varchar(255) NOT NULL,
    title         varchar(255) NOT NULL,
    raw_text      text         NOT NULL,
    doc_date      varchar(255) NOT NULL,
    author        varchar(255),
    external_ref  varchar(255),
    created_at    timestamp(6) with time zone NOT NULL
);
CREATE INDEX idx_sources_tenant_initiative ON sources (tenant_id, initiative_id);

CREATE TABLE events (
    id                  varchar(255) PRIMARY KEY,
    tenant_id           varchar(255) NOT NULL REFERENCES tenants (id),
    initiative_id       varchar(255) NOT NULL,
    source_id           varchar(255) NOT NULL,
    event_type          varchar(255) NOT NULL,
    summary             text         NOT NULL,
    decided_by          varchar(255),
    event_date          varchar(255) NOT NULL,
    status              varchar(255) NOT NULL,
    supersedes_event_id varchar(255),
    confidence          varchar(255) NOT NULL,
    created_at          timestamp(6) with time zone NOT NULL
);
CREATE INDEX idx_events_tenant_initiative ON events (tenant_id, initiative_id);

-- Owned collection, reachable only through its parent event. It carries no tenant_id of
-- its own because Hibernate never queries it independently - it is always loaded via a
-- tenant-filtered Event - and an unmanaged NOT NULL column here would break inserts.
CREATE TABLE affected_items (
    event_id  varchar(255) NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    item_name varchar(255)
);
CREATE INDEX idx_affected_items_event ON affected_items (event_id);

CREATE TABLE "constraints" (
    id                 varchar(255) PRIMARY KEY,
    tenant_id          varchar(255) NOT NULL REFERENCES tenants (id),
    initiative_id      varchar(255) NOT NULL,
    source_event_id    varchar(255) NOT NULL,
    statement          text         NOT NULL,
    reason             text,
    status             varchar(255) NOT NULL,
    lifted_by_event_id varchar(255),
    created_at         timestamp(6) with time zone NOT NULL
);
CREATE INDEX idx_constraints_tenant_initiative ON "constraints" (tenant_id, initiative_id);

CREATE TABLE contradictions (
    id            varchar(255) PRIMARY KEY,
    tenant_id     varchar(255) NOT NULL REFERENCES tenants (id),
    initiative_id varchar(255) NOT NULL,
    event_ida     varchar(255) NOT NULL,
    event_idb     varchar(255) NOT NULL,
    description   text         NOT NULL,
    resolved      boolean      NOT NULL,
    created_at    timestamp(6) with time zone NOT NULL
);
CREATE INDEX idx_contradictions_tenant_initiative ON contradictions (tenant_id, initiative_id);

CREATE TABLE ticket_branch_links (
    id                   varchar(255) PRIMARY KEY,
    tenant_id            varchar(255) NOT NULL REFERENCES tenants (id),
    jira_connection_id   varchar(255) NOT NULL,
    github_connection_id varchar(255) NOT NULL,
    ticket_key           varchar(255) NOT NULL,
    repo_full_name       varchar(255) NOT NULL,
    branch_name          varchar(255) NOT NULL,
    branch_sha           varchar(255),
    status               varchar(255) NOT NULL,
    created_at           timestamp(6) with time zone NOT NULL,
    last_checked_at      timestamp(6) with time zone,
    -- The old constraint was (repo_full_name, ticket_key). Two tenants tracking a repo of
    -- the same name - or one tenant with the same repo under two GitHub accounts - would
    -- collide on it and overwrite each other.
    CONSTRAINT uk_ticket_branch_link UNIQUE (tenant_id, github_connection_id, repo_full_name, ticket_key)
);
CREATE INDEX idx_ticket_links_tenant_key ON ticket_branch_links (tenant_id, ticket_key);

-- Bootstrap tenant. An ordinary tenant with no cross-tenant privileges; it exists only so
-- a fresh install has somewhere to create its first user. The id is fixed rather than
-- random so this migration is identical on every machine.
INSERT INTO tenants (id, name, slug, created_at)
VALUES ('00000000-0000-0000-0000-000000000000', 'Root', 'root', now());
